name: Compilar APK Android
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Preparar y Compilar APK
        run: |
          cd keto-tracker
          # Respaldar manifiesto con permisos de Health Connect
          cp android/app/src/main/AndroidManifest.xml /tmp/AndroidManifest.xml
          rm -rf android

          # Instalar Capacitor y generar proyecto nativo
          npm install @capacitor/core@latest @capacitor/android@latest @capacitor/cli@latest --save

          npx cap add android

          # Restaurar manifiesto con permisos de Health Connect
          cp /tmp/AndroidManifest.xml android/app/src/main/AndroidManifest.xml

          npx cap sync android

          # Compilar el archivo APK
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: KetoTrack-Android-APK
          path: keto-tracker/android/app/build/outputs/apk/debug/app-debug.apk
